### ISSUE TITLE
Admin endpoint

### ISSUE THREAD

**Issue by Emibrown** [coinratecap/Backend#14]
Our next target is to create endpoint to enable admin carry put the following functionalities.

1 Add, Edit, Delete of coin form the database
2 Add, Edit, Delete of exchanges from the database
3 Assign coin to exchanges
4 Add, Edit, Delete of blog post

@Wisdom132 will handle -- 1
@NoorAhmd  will handle -- 2
@melodyogonna  will handle --- 3
@Emibrown will handle -- 4

We have to complete all the above task within 24hours from now.

**Comment by Emibrown** [comment]
But first @Wisdom132 you have to setup authentication for the Admin.

**Comment by NoorAhmd** [comment]
@Emibrown do we have exchange collection ready in DB?

**Comment by Emibrown** [comment]
@NoorAhmd yes we have the exchange collection setup already https://github.com/coinratecap/Backend/blob/main/src/modules/models/Exchanges.js

**Comment by melodyogonna** [comment]
How does assigning coins to exchanges work?

**Comment by Emibrown** [comment]
@melodyogonna  The exchange schema is referencing an array of coin, all you need to do is create an endpoint that accept multiple or single coin by _id and push them to the coin field on the exchange schema.

**Comment by melodyogonna** [comment]
Oh, cool. So it accepts an array of coin ids or single coin id.

**Comment by melodyogonna** [comment]
@Emibrown I can't find the coin field in the exchanges schema

**Comment by Emibrown** [comment]
@melodyogonna please create one and make it an array of Coin ID

` coin: [{
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Coin'
        }]`
