### ISSUE TITLE
Get Historical Data from CoinmarketCap of all cryptocurrencies

### ISSUE THREAD

**Issue by hussu010** [coinratecap/Backend#6]

**Comment by hussu010** [comment]
we'll use the API endpoint https://web-api.coinmarketcap.com/v1.1/cryptocurrency/quotes/historical?convert=USD,BTC&format=chart_crypto_details&id={{coin_id}}&interval=daily&time_end=1609643973&time_start=1300000000 to access the historical data of the coins.
To get the id of the coins: https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=5000 (header X-CMC_PRO_API_KEY needs to be passed to access the API)

**Comment by sangameshBB** [comment]
I think SLA for this first API is 1 sec per coin per call, how should we improve on it? As we cannot have more rendering time.

**Comment by Francaolisa** [comment]
We cannot use api endpoints to get historical data.
