### ISSUE TITLE
List the data that needs to be analyzed

### ISSUE THREAD

**Issue by Francaolisa** [coinratecap/Backend#67]
Going through the exchange api, mention the following that's not provided by the exchange Api but rather requires data analysis to come up with the information.

 For instance, we have the LAST PRICE in this exchange api https://api.binance.us/api/v3/ticker/24hr?symbol=BTCUSD
as the price of Bitcoin, same as volume etc.

In the information provided below for each coin, which of them are not literally stated in the api?

Price | 1h | 24h | 7d | 24h Volume | Mkt Cap | Last 7 Days | Market Cap | 24h Low / 24h High |Circulating Supply | Fully Diluted Valuation | Max Supply|

**Comment by hussu010** [comment]
We will only get the price and volume of the coin from the exchange API. Every other data needs to be analyzed.

**Comment by Francaolisa** [comment]
Alright

**Comment by NoorAhmd** [comment]
1: https://api-public.sandbox.pro.coinbase.com/products/BTC-USD/ticker
--> Price and volume are provided. Some other fields like "ask" and "bid" are also there for analyze

2: https://api.kraken.com/0/public/Ticker?pair=BTCUSD
--> The response format is very different from other resources. This needs to be analyzed.

3: https://api-pub.bitfinex.com/v2/tickers?symbols=tBTCUSD
--> In response, field name are not provided. This needs to be analyzed.

4: https://ftx.com/api/markets/BTC/USD
--> Very detailed response provided. No need to be  analyzed.

5: https://api.binance.us/api/v3/ticker/24hr?symbol=BTCUSD
--> Binance is providing really good formated response. No need to be  analyzed.

6: https://api.gemini.com/v1/symbols
--> Only names of the coins without any value or price. We can not use this.

7: https://api-public.sandbox.pro.coinbase.com/products
--> Very detailed response provided. No need to be  analyzed.

8: https://api.kraken.com/0/public/AssetPairs
--> The response format is complex but its also detailed. Needs to be analyzed.

9: https://api-pub.bitfinex.com/v2/tickers?symbols=ALL
--> Only prices are provided without naming the fields. Needs to be analyzed.

10: https://api.binance.us/api/v3/exchangeInfo
--> More about the exchange info and number of orders. No information and coin's prices. Needs to be analyzed.

11: https://api.gemini.com/v1/pubticker/btcusd
--> Price and volume are provided. Other fields may get analyzed.
